### ISSUE TITLE
Can't start streaming

### ISSUE THREAD

**Issue by ahmadd110** [JRoy/InstagramLive-PHP#202]
Dear JRoy
I can log into my account but can't start streaming. The following error is displayed

C:\xampp\htdocs\v2.0>php goLive.php
Loading InstagramLive-PHP v2.0-stable (66)...
Login: Starting Instagram logon, please wait...
Login: Successfully logged in as live2019fdgdsf!
Livestream: Creating livestream...
Error: An error occurred during livestream initialization.
===========BEGIN DUMP===========
InstagramLive-PHP Version: 2.0
InstagramLive-PHP Flavor: stable
Instagram-API Version: dev-master#502a89aceed92595514d5c381e36176985abb977
Operating System: WINNT
PHP Version: 7.3.10
PHP Runtime: cli
PHP Binary: C:\xampp\php\php.exe
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true
Request Endpoint: live/create/
Exception: InstagramAPI\Response\CreateLiveResponse: Login required.
============END DUMP============

**Comment by mr-asymmetric** [comment]
Dear JRoy,

I have the same issue


PS C:\xampp\IGlive> C:\Users\Administrator\Desktop\Live IG.ps1
Loading InstagramLive-PHP v2.0-stable (66)...
Login: Starting Instagram logon, please wait...
Error while logging into Instagram: No response from server. Either a connection or configuration error.
===========BEGIN DUMP===========
InstagramLive-PHP Version: 2.0
InstagramLive-PHP Flavor: stable
Instagram-API Version: dev-master#502a89aceed92595514d5c381e36176985abb977
Operating System: WINNT
PHP Version: 7.3.9
PHP Runtime: cli
PHP Binary: C:\xampp\php\php.exe
Bypassing OS-Check: true
Composer Lock: true
Vendor Folder: true
Request Endpoint: discover/topical_explore/
Exception: No response from server. Either a connection or configuration error.
============END DUMP============

**Comment by JRoy** [comment]
Yikes I'll have a look into this

**Comment by yanza07** [comment]
Dear JRoy
i have logon issue 

Suspicious Login: Account Challenge Failed :(.
===========BEGIN DUMP===========
InstagramLive-PHP Version: 2.0
InstagramLive-PHP Flavor: stable
Instagram-API Version: dev-master#502a89aceed92595514d5c381e36176985abb977
Operating System: WINNT
PHP Version: 7.3.11
PHP Runtime: cli
PHP Binary: C:\xampp\php\php.exe
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true
Exception: Throttled by Instagram because of too many API requests.
============END DUMP============

have i do something wrong  ?

**Comment by JRoy** [comment]
This can be solved by re-running the script for now.
