### ISSUE TITLE
Can't login 

### ISSUE THREAD

**Issue by singletpetir** [JRoy/InstagramLive-PHP#207]
Dear JRoy,

i can't logon and start streaming 

C:\liveInstagram\InstagramLive-PHP-Ashiiltv>php golive.php -f
Loading InstagramLive-PHP v2.0-stable (66)...
Login: Starting Instagram logon, please wait...
Suspicious Login: Would you like to verify your account via text or email? Type "yes" or just press enter to ignore.
Suspicious Login: Please only attempt this once or twice if your attempts are unsuccessful. If this keeps happening, this script is not for you :(.
>

please help with my problem...
i already update the php

**Comment by JRoy** [comment]
Did you try typing yes?

**Comment by ChorizoIberico** [comment]
Same problem!
C:\xampp\htdocs\InstagramLive-PHP-master>php goLive.php
Loading InstagramLive-PHP v2.0-stable (66)...
Login: Starting Instagram logon, please wait...
Suspicious Login: Would you like to verify your account via text or email? Type "yes" or just press enter to ignore.
Suspicious Login: Please only attempt this once or twice if your attempts are unsuccessful. If this keeps happening, this script is not for you :(.
> yes
Suspicious Login: Preparing to verify account...
Suspicious Login: Please select your verification option by typing "sms" or "email" respectively. Otherwise press enter to abort.
> email
Suspicious Login: Please enter the code you received via email...
> (AND NOTHING ARRIVES)

**Comment by JRoy** [comment]
Closing due to no response.
