### ISSUE TITLE
Flagged account

### ISSUE THREAD

**Issue by hasanitman** [JRoy/InstagramLive-PHP#34]
Hello
I get flagged account with the script
I try the verification code, but after it, when i login with script, again want verification
I check it more than 10 time
And i login with website too.
Do u have solution?
Thank you

**Comment by skt1dev** [comment]
I had this problem once and it was because instagram detected "unusual logins attempts" from the script. I verified my account with SMS method and problem solved.

Also, I read in #31 that you are working with xampp in windows.. I like xampp, but it is meant for development purposes. I recommend you to try installing PHP and Composer manually and then run the script just like it is explained in the setup steps in the code page.

I run the script in windows that way, I'm still using v0.5 and no problems at all.

**Comment by hasanitman** [comment]
If i install php alone, maybe i have better chance?
I verify my account more than 10 with sms but no success, every time i connect, i get this error
