### ISSUE TITLE
Works but not I need help!

### ISSUE THREAD

**Issue by oscarlmadrid** [JRoy/InstagramLive-PHP#40]
Hi guys, I did all in Mac and it works but I can't see nothing on my instagram account, so it I go to instagram with another account i can see my profile on live, but the screen is in black, no video, no sound, nothing, and then instagram shows a message that they have problems to load that video...

**Comment by JRoy** [comment]
Are you streaming on obs? If so what are your obs settings

**Comment by JRoy** [comment]
Are you streaming on obs? If so what are your obs settings

**Comment by JRoy** [comment]
No Response in a Week, Closing

**Comment by AnitaPazhohesh** [comment]
Hi Josh,
Hope all is well and thanks again for your great job creating working scripts for Instagram Live.
Would you please let me know when release 7 goes out and what kind of new features for Instagram Live streaming are included in the latest release?
I’ve been following you since the 1st release. I have release 5 installed on my PC since 4 months ago, how can I replace that with the latest release to use new features? If I just replace the current folder on my Windows 7 with the new one containing the new released files, would it work? Or other changes required?
Anita

**Comment by JRoy** [comment]
Hi @AnitaPazhohesh

It is recommended you repeat the setup instructions each time you update as multiple files can change per release. Additionally, we have a discord server: [https://discord.gg/EpkKFt3](https://discord.gg/EpkKFt3) I have a channel dedicated to posting release information if you'd like to know as soon as 0.7 is available

**Comment by AnitaPazhohesh** [comment]
I just noticed that few tv channels who use the script had turned OFF the viewer comments during their live streams on Instagram! How can I do that as the comments cover portion of the screen?
Thanks!
Anita

**Comment by AnitaPazhohesh** [comment]
Is there a command to turn off the comments on Instagram live?

**Comment by JRoy** [comment]
@AnitaPazhohesh Yes, `dcomments`

You can do `help` for a list of commands

**Comment by AnitaPazhohesh** [comment]
Thanks much Josh for your quick responses,
I still don’t understand that your latest release will enable non stop live streaming on Instagram or what exactly the new feature does when you mentioned “properly handle 1 hour time limit”?!

**Comment by AnitaPazhohesh** [comment]
Also, the new -i command to auto start a new live stream works with the older version of your script too?

**Comment by JRoy** [comment]
@AnitaPazhohesh you must use the beta version to try these features...The script will generate a new key automatically now

**Comment by JRoy** [comment]
Run the script with -d and give me the details it says please

**Comment by AnitaPazhohesh** [comment]
Sure. Should I go live first to try this command or not?

**Comment by AnitaPazhohesh** [comment]
I run the -d command and new windows opens for commands but when I enter Help, the -i command is not included in the displayed list!?

**Comment by JRoy** [comment]
You must reinstall you script for the latest features

**Comment by AnitaPazhohesh** [comment]
Dear Josh,
Thanks for your quick responses. Just one more issue:
When I get the stream key from Instagram on cmd window, the key is not like one peace of code but rather has spaces in between! I have to copy the key, paste it into note pad every time and delete or back space the spaces between key codes and then copy the whole one piece key again for streaming on OBS or Wirecast. Why is that? Any suggestion to fix this and save me time copying and pasting the key faster?
Much Appreciation.

**Comment by AnitaPazhohesh** [comment]
Hi Josh,

You’re doing a great job as always.
One question though: with version 9, can we use other streaming softwares like Wirecast instead of OBS for auto run and to use the latest features?!

Regards,
Anita

**Comment by JRoy** [comment]
@AnitaPazhohesh for now I'm only supporting OBS as it's easier to support and it's all I currently know the configurations for. I may add support for different streaming softwares but that would not be planned sorry

**Comment by AnitaPazhohesh** [comment]
Hello Josh,
Hope all is well.
Since yesterday we’re not able to go Live on Instagram through the php script!! We have been doing Live every day before with no problem. The script runs as usual, connects to servers and it even gives us the stream key but once we start the encoder it disconnects and gives us error! I also checked 2 other tv channels that goes live on Insta like us every day but they also are OFF since yesterday! Do you know what’s happening? Is Instagram has changed anything for Live through php? Just to let you know that we can go Live on the phone by Instagram app though! Any advice on the solution?
Thanks!

**Comment by AnitaPazhohesh** [comment]
Hello Josh,
Can you please help me out on this:
How can I use some of the commands for live streaming? Where exactly should I type the required commands? Im interested in the one that bypass the 1 hour limit for live so I can go live for 2 hours with no cutoff.
Thanks much.
Great job with the script updates as always.
